# ContainerPy.pyi
from typing import List

class Package:
    def __init__(self, id: str) -> None: ...
    def get_package_id(self) -> str: ...
    def set_package_id(self, id: str) -> None: ...

class Container:
    def __init__(self, id: str, size: int) -> None: ...
    def get_container_id(self) -> str: ...
    def set_container_id(self, id: str) -> None: ...
    def get_container_size(self) -> int: ...
    def set_container_size(self, size: int) -> None: ...
    def add_package(self, package: Package) -> None: ...

class ContainerMap:
    def __init__(self) -> None: ...
    def __init__(self, dbLocation: str) -> None: ...
    def add_container(self, container: Container, addingTime: float) -> None: ...
    def add_containers(self, containers: List[Container], addingTime: float) -> None: ...
    def get_container(self, id: str) -> Container: ...
    def remove_container(self, id: str) -> None: ...
    def get_all_containers(self) -> List[Container]: ...
    def get_latest_containers(self) -> List[Container]: ...
    def size(self) -> int: ...
    def get_containers_by_added_time(self, referenceTime: float, condition: str) -> List[Container]: ...
    def dequeue_containers_by_added_time(self, referenceTime: float, condition: str) -> List[Container]: ...
    def get_containers_by_next_destination(self, destination: str) -> List[Container]: ...
    def dequeue_containers_by_next_destination(self, destination: str) -> List[Container]: ...
